### ISSUE TITLE
Multivariate Regression

### ISSUE THREAD

**Issue by Dashadower** [bbbales2/regressions#35]
This is another one of these 'oof' parts that's non-trivial to solve. Like what Bob said in his email, I initially thought there would be no syntactically clean way to write it out without any form of ambuiguity. But let's see what options we have:

This is the varying-intercept, varying-slope radon model from Andrew's book, *Data Analysis Using Regression*, p. 279:

![image](https://user-images.githubusercontent.com/10173396/145214202-65f9d7b4-5972-4b35-8e38-2a95a7ecac16.png)

The crux is we assume that `beta` is a vector of length `J`, that's subscripted by group. _Think as if subscripted parameters are vectors/matrices_.

Lets try writing the model in rat assuming the necessary distributions and multidimensional data types are implemented:

```
y ~ normal(alpha[group] + beta[group] * x, sigma_y);
corr_sigma[2, 2] = {{sigma_alpha, rho * sigma_alpha * sigma_beta}, 
                    {rho * sigma_alpha * sigma_beta, sigma_beta}}
{alpha[group], beta[group]} ~ mvnormal({mu_alpha, mu_beta}, corr_sigma);
```

Given that we can assign vectors/matrices, we can treat subscripts as indexing a vector. However, if we have hundreds of response variables, this can be a pain to write out, while languages that allow loops like stan can loop over them.

----

Let's take the notion of treating subscripted parameters as vectors a step further. Say we would like to change the above model and assume that components of `beta` are correlated with each other. Assume there exists an ordering scheme for subscripted parameters. Since we treat `beta` by itself as a vector, one way we might write the model is:
```
beta ~ mvnormal(mu_beta, corr_beta);
mu_beta[4] ~ normal(0, 1);
corr_beta[4, 4] ~ LKJ(1.0);
```

This will work because the rat compiler will evaluate subscripts before actually evaluating the expressions. So at evaluation phase the compiler knows variable `beta` was defined to be a length 4 vector, matching the signature of the rhs mvnormal.

---

This time we're going to explore *vector parameters* and see how we can model correlation between them. Take the example model from [here](https://mc-stan.org/docs/2_28/stan-users-guide/multivariate-hierarchical-priors.html#likelihood). So we're modeling a vector parameter `beta` of length 4, that exists for each subscript `group`. We would like to model that components of `beta[group]` are correlated.  If we allow creating vector parameters with subscripts, so `beta[group, 4]` means a vector parameter of length 4 for each group, we can try the following syntax(To be clear, `:` in **indexes** denote the dimension at the given index, like numpy):

```
y ~ normal(alpha + x_1 * beta[group, 1] + x_2 * beta[group, 2]+ x_3 * beta[group, 3]+ x_4 * beta[group, 4]   , sigma);
beta[group, :] ~ MVNormal(mu[group], corr_sigma);
corr_sigma[4, 4] ~ LKJ(1.0);
```

I hope this resolves some ambiguities regarding multidimensional parameters and correlation modeling.

---

Let's write out the BNF grammar for defining subscripted multidimensional parameters:
```
constraint ::= ?('<' constraint_range '>')
atomic_statement ::=  lhs assignmentOp expression ';'
subscripts ::= identifier % ','
dimensions ::= integer % ','
             |  ':' % ','
lhs ::= identifier[subscripts, dimensions] constraint
``` 

Although we describe the dimension within the same brackets that we define subscripts, we can differentiate between them by checking that subscripts are identifiers that denote columns within the data while dimensions are expression that return an integer.

**Comment by Dashadower** [comment]
I've revised the above writeup to be more precise:

# Multidimensional, Multivariate Variables

This is a write-up on a proposed implementation and syntax details regarding multidimensional and multivariate variables. My intent is to keep as close as possible to the mathematical syntax of defining hierarchical bayesian models, while being free from ambuigities regarding syntax and semantics. Note this is tentative and prone for error; I'd love for counterexamples where the proposed syntax/semantics fail.

## Kicking it off with an example

![](https://i.imgur.com/aIbA8y8.png)
This is a varying-intercept, varying-slope model from p. 490 of BDA. We model parameters `alpha, beta` for each group `j`. Let's say we're using wide-form data, which means we have the following data format:

| y    |   x   |   j    |
|------|:-----:|-------:|
| 0.54 | 0.01  |   1    |
| 0.26 | 0.022 |   2    |
| 0.4  | 0.08  |   3    |


So we have  `J` different groups, meaning `J = max(data$j)`

We can write the model in rat as the following code(I've ommited hyperprior statements for the sake of simplicity; assume we have defined them for each parameter):

```
y ~ normal(alpha[j] + x * beta[j], sigma_y);
corr_sigma[2, 2] = {{sigma_alpha, rho * sigma_alpha * sigma_beta}, 
                    {rho * sigma_alpha * sigma_beta, sigma_beta}};
{alpha[j], beta[j]} ~ mvnormal({mu_alpha, mu_beta}, corr_sigma);
```

I'll give a line-by-line explanation of how rat compiles the model:

1. In line 1, we see that `alpha[j]`, `beta[j]` are both subscripted by `j`, which denotes the group index column in the data. This implies that `alpha, beta` exists for each group `j` in `J`. **Notice how we used only right-hand-sides of statements to deduce subscripts.** 
2. Line 2 creates a 2 by 2 matrix manually defined by the user. Note that `corr_sigma[2, 2]` aren't subscripts, but dimensions/indexes in the traditional sense, since the values within the brackets are just integer expressions.
3. The lhs of line 3 creates a length-2 vector consisting of parameter alpha and beta for each group. This vector is sampled from a mulivariate normal distribution with the designated mean vector on the rhs and the defined covariance matrix.

## Subscripts vs Indexes

Say we have a parameter `beta` that's a vector of length `J` and for the sake of this example let's say `J = 4`. How will we define the lengh of `beta`? `beta[4]` wouldn't work, because it's identical to indexing the 4th indexed element of the vector. Consider the case where we use `beta` in rhs first:

```
y ~ normal(beta * x, sigma);
# is equivalent to:
y ~ normal(beta[1] * x[1] * beta[2] * x[2] * beta[3] * x[3] + beta[4] * x[4], sigma);
```

Using just `beta` refers to the length `J` vector. But the brackets denote indexing the `j`th component.

Now let's look at when it's being used in rhs:

```
beta ~ normal(0.0, 1.0);
```

This code assumes all the components of the vector to follow a unit normal distribution. If we combine the code with the snippet above:

1-1
```
y ~ normal(beta * x, sigma);
beta ~ normal(0.0, 1.0);
```

which is equivalent to:
1-2
```
y ~ normal(beta[1] * x[1] * beta[2] * x[2] * beta[3] * x[3] + beta[4] * x[4], sigma);
beta ~ normal(0.0, 1.0);
```

Code 1-2 doesn't seems to show problems when deducing the size of beta, since we know from the first line that beta was indexed from 1 up to the 4th component.

But in code 1-1, How do we deduce that `beta` is a vector parameter? One might argue
```
beta[4] ~ normal(0.0, 1.0);
```
is a way to do it. But this also implies that just the 4th index component is drawn from a normal distribution. 
Therefore I propose that we force _explicit indexing_. That is, instead of just calling `beta` to refer to the length 4 vector, the user must refer to it with `beta[1:4]` so code 1-1 would become:

1-1-2
```
y ~ normal(beta[1:4] * x[1:4], sigma);
beta[1:4] ~ normal(0.0, 1.0);
```

Well then you might ask if we can we call do something like:

```
y ~ normal(beta[3] * x[3], sigma);
beta[1:4] ~ normal(0.0, 1.0);
```
We can't, because in rat, subscripts and indexes are fully known when evaluating the statement, except for assignments. Since we haven't referred `beta[1], [beta[2], beta[4]`, they do not exist in the program state.

## Multivariate Subscripted-Multidimensional Parameters

We combine the notion of subscripts and explict indexes to enable us to declare vector parameters for each groups that are correlated within groups or between groups.

The first model we'll take as an example is from [stan's docs](https://mc-stan.org/docs/2_28/stan-users-guide/multivariate-hierarchical-priors.html#likelihood):

![](https://i.imgur.com/qfR9n6v.png)

For each group `j` there exists a vector of parameters `beta` that's correlated within group. Assume there are 4 regression coefficients(K = 4). We can express that in rat as:

```
y ~ normal(x[1:4] * beta[group, 1:4], sigma);
beta[group, 1:4] ~ mvnormal(beta_mu[group, 1:4], cov_beta);
beta_mu[group, 1:4] ~ normal(0.0, 1.0);
cov_beta[1:4, 1:4] = diag(tau[1:4]) * omega[1:4, 1:4] * diag(tau[1:4]);
tau[1:4]<lower=0.0> ~ cauchy(0, 2.5);
omega[1:4, 1:4] ~ LKJ(1);
```

Having to type the indexes every time the variable is referred can be frustrating. But this is necessary for two reasons:
1. _rat doesn't rely on assignment statements_. If we look at the code above, we've explicitly assigned just one variable, `cov_beta`. Other necessary parameters are inferred by subscript evaluation. This has the disadvantage that dimensions aren't declared from a single statement and thus explicit indexing is required to correctly construct the indexing set.
2. _Explicit indexes allow users to specify detailed prior on individual components_. If we wanted model that only the 1st, 2nd, 4th coefficients are correlated, we can specify the following:
```
y ~ normal(x[1:4] * beta[group, 1:4], sigma);
beta[group, [1, 2, 4]] ~ mvnormal(beta_mu[group, 1:3], cov_beta);
beta[group, 3] ~ normal(0, 1);
beta_mu[group, 1:3] ~ normal(0.0, 1.0);
cov_beta[1:3, 1:3] = diag(tau[1:3]) * omega[1:3, 1:3] * diag(tau[1:3]);
tau[1:3]<lower=0.0> ~ cauchy(0, 2.5);
omega[1:3, 1:3] ~ LKJ(1);
```

---

Let's write out the BNF grammar for defining subscripted multidimensional parameters:
```
constraint ::= ?('<' constraint_range '>')
atomic_statement ::=  lhs assignmentOp expression ';'
integer_seq ::= integer % ','
subscripts ::= identifier % ','
dimensions ::= integer % ','
             | integer ':' integer % ','
             | '[' integer_seq ']'
lhs ::= identifier[subscripts, dimensions] constraint
``` 

Although we describe the dimension within the same brackets that we define subscripts, we can differentiate between them by checking that subscripts are identifiers that denote columns within the data while dimensions are expression that return an integer.

**Comment by bbbales2** [comment]
I like the logic here, especially:

> That is, instead of just calling beta to refer to the length 4 vector, the user must refer to it with beta[1:4] so code 1-1 would become

and

> Since we haven't referred beta[1], [beta[2], beta[4], they do not exist in the program state.

Otherwise a couple comments

-----

For this statement:
```
corr_sigma[2, 2] = {{sigma_alpha, rho * sigma_alpha * sigma_beta}, 
                    {rho * sigma_alpha * sigma_beta, sigma_beta}};
```

Shouldn't this be unambiguous?
```
corr_sigma = {{sigma_alpha, rho * sigma_alpha * sigma_beta}, 
                    {rho * sigma_alpha * sigma_beta, sigma_beta}};
```

I also don't expect many correlation matrices to get written manually, and instead everything to be like:
```
corr_sigma ~ lkj(2.5); 
```

And that doesn't have size information in it. If we were going by sizes-come-from-use, then I think somehow the size of corr_sigma needs inferred from:
```
{alpha[j], beta[j]} ~ mvnormal({mu_alpha, mu_beta}, corr_sigma);
```

-----

This makes sense in rat syntax, but for the multivariate regression problem x is coming from a long-form dataframe:

```
y ~ normal(x[1:4] * beta[group, 1:4], sigma);
```

So instead of the dataframe looking like:
```
y, x, i
[1, 2, 3, 4], [2, 3, 4, 5], 1
...
```

It would be:
```
y, z, i, j
1, 2, 1, 1
2, 3, 1, 2
3, 4, 1, 3
4, 5, 1, 4
...
```

And the calculation is more like:
```
y ~ normal(sum_over_i(x[i] * beta[group, i]), sigma);
```

That sum_over_i function is awkward, but this reminds me of https://en.wikipedia.org/wiki/Einstein_notation. In that we'd have something like:
```
y ~ normal(x[i] * beta[group, i], sigma);
```

This would define the variables nicely, but the problem there is that the names of our subscripts are tied to the dataframe, so there'd be no way to choose between `x[i] * beta[group, i]` meaning sum over i and don't sum over i without extra syntax.

This makes me think along the lines of the stuff over [here](https://github.com/bbbales2/regressions/issues/34#issuecomment-991750713), where we have groupbys and whatnot. Because the underlying calculations are done on dataframes this would be implemented as groupbys and aggregates, so I think it's the way to think (and hopefully the translation to Jax is still clean).

**Comment by Dashadower** [comment]
Forgive me if I got you wrong(my brain has burned out after recent final exams), but I don't understand 
```
y, x, i
[1, 2, 3, 4], [2, 3, 4, 5], 1
```
and equivalently,
```
y, z, i, j
1, 2, 1, 1
2, 3, 1, 2
3, 4, 1, 3
4, 5, 1, 4
...
```
what these dataframes imply. In the second dataframe, for each y(1, 2, ...), shouldn't they share the same independent variable vector `[2, 3, 4, 5]`, if the independent variables are the same per group?

In my original comment:
```
y ~ normal(x[1:4] * beta[group, 1:4], sigma);
```
This essentially described a linear regression without intercept for `y = normal(\mathbf{x} \cdot \mathbf{\beta}, \sigma)`:
![image](https://user-images.githubusercontent.com/10173396/146187378-cfcc1006-5cb3-462e-9912-7c5ee40431cb.png)

> This would define the variables nicely, but the problem there is that the names of our subscripts are tied to the dataframe, so there'd be no way to choose between x[i] * beta[group, i] meaning sum over i and don't sum over i without extra syntax.

By this do you mean whether it's a scalar multiplication (product 'i'th value) vs dot product along i?

**Comment by bbbales2** [comment]
> shouldn't they share the same independent variable vector [2, 3, 4, 5], if the independent variables are the same per group?

The way I read that is that in the first y and z are vectors, and each element of y corresponds to an element in z (rather than every element in y corresponds to the entire vector z).

> whether it's a scalar multiplication (product of 'i'th value) vs dot product along i

Yeah

**Comment by bbbales2** [comment]
> In my original comment:

I guess I was comparing long form dataframes to having vectors as elements in a dataframe if that helps.

**Comment by Dashadower** [comment]
> > shouldn't they share the same independent variable vector [2, 3, 4, 5], if the independent variables are the same per group?
> 
> The way I read that is that in the first y and z are vectors, and each element of y corresponds to an element in z (rather than every element in y corresponds to the entire vector z).

Ah okay. Then if the data is in long-form data and each y only depends on the z value that's on the same row, what role does `sum_over_i` do in the following line?
```
y ~ normal(sum_over_i(x[j] * beta[group, j]), sigma);
```

**Comment by bbbales2** [comment]
Ooo, I meant that to be sum_over_j not i (so it's doing an inner product). Changing it in the text now.
