### ISSUE TITLE
Multiple line programs don't parse correctly

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#39]
Might just be a problem with how we're passing strings to the parser, see [here](https://github.com/bbbales2/regressions/blob/main/rat/model.py#L132)

**Comment by bbbales2** [comment]
Here's a program that'll cause the current setup to go into infinite loop:
```
y ~ bernoulli_logit(
  a +
  b
);
```

**Comment by Dashadower** [comment]
Yeah right now it uses just newline as separation characters. I'm working on some scanner modifications which better implements the grammar.

**Comment by Dashadower** [comment]
I'm closing this since I'm certain this has been fixed. Feel free to reopen if it happens again.
