### ISSUE TITLE
No priors on parameters throw not-super-informative errors

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#43]
Here's code. Remove the two commented lines to see the two different errors:

```python
df = pandas.DataFrame({ "abortion" : [0], "state" : [1] })

model_string = """
abortion ~ bernoulli_logit(a_state[state]);
a_state[state] = a_state_z[state] * sigma_state;
a_state_z[state] ~ normal(0, 1.0); # Remove this line and you'll see an error about the index for a_state_z not existing
sigma_state<lower = 0.0> ~ normal(0.0, 1.0); # Remove this line and you'll still get an error but a different one
"""

model = Model(df, model_string=model_string)
```

I think parameters with no priors should throw warnings. We could go pedantic and require a prior, but seems simpler to just log a warning.

Here is one of the errors as an example:
```
  File "/home/bbales2/regressions/rat/compiler.py", line 271, in compile
    parameter_base_df[target_op_name].columns = tuple(target_op_index_key)
TypeError: 'NoneType' object is not iterable
```

**Comment by Dashadower** [comment]
Hmm. I think removing 
```
a_state_z[state] ~ normal(0, 1.0);
```
should throw an error. The assignment line does assume a_state_z exists. IMO not requiring a prior equates to implicit declaration which looks more prone to coding errors. But I guess if warnings suffice then I'm on board.

With that said when implementing, I think this would become "if a variable on RHS is not present, immediately create a parameter with said name and subscript that follows some default distribution".

**Comment by bbbales2** [comment]
I don't think we require priors on parameters yet. Anyway this can close and we can come back whenever.
