### ISSUE TITLE
Issue with subscript order

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#45]
I was getting errors with an assignment arranged like:

```
mu[state, age] = param[age, state];
```

Index swapping like this should be allowed.

**Comment by Dashadower** [comment]
So like #47, do you suggest we throw a warning whenever the user mixes up subscript names? I'm skeptical if this would be possible to identify 100% of the time, since if you think about the baseball example, we use positional subscripts to identify `team` implies `home_team` and `away_team`

**Comment by bbbales2** [comment]
I think the statement here should be legal -- it's two different variables on each side of that assignment.

In 47 it's one variable be referenced in a weird way. Like when the variable is the same, the positioning is really important (because of renaming it's actually more important than the name). For different variables, the name is more important than the positioning.

**Comment by bbbales2** [comment]
Doesn't seem to be a problem anymore.
