### ISSUE TITLE
Issue with check_and_return_index

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#46]
I had a problem with:
```
df_index = (
  op.index.get_key() if isinstance(lhs, ops.Data) else lhs.variable.index.check_and_return_index(op.index.get_key())
)
```

The get_key value was `("age",)`, but the check_and_return_index was returning `("age", "educ",)`.

**Comment by Dashadower** [comment]
Is this from the MRP model code?

**Comment by bbbales2** [comment]
Yes sorry for no repro -- I can look at getting you one in a bit.

**Comment by Dashadower** [comment]
I've debugged through the MRP model but I couldn't reproduce the error. The compiler identified the usage of subscripts on the RHS and correctly matched it to the reference subscripts of the LHS variable:

print order is: (original RHS variable's subscript key), (result of applying LHS's `check_and_return_subscripts` to RHS subscript key)
```
DEBUG:root:a_male_eth, ('male', 'eth'), ('male', 'eth')

DEBUG:root:a_age_z, ('age',), ('age',)

DEBUG:root:a_age, ('age',), ('age',)

DEBUG:root:a_educ_z, ('eth',), ('eth',)

DEBUG:root:a_educ, ('educ',), ('educ',)

DEBUG:root:a_educ_eth_z, ('educ', 'eth'), ('educ', 'eth')

DEBUG:root:a_educ_eth, ('educ', 'eth'), ('educ', 'eth')

DEBUG:root:a_eth_z, ('eth',), ('eth',)

DEBUG:root:a_eth, ('eth',), ('eth',)

DEBUG:root:a_educ_age_z, ('educ', 'age'), ('educ', 'age')

DEBUG:root:a_educ_age, ('educ', 'age'), ('educ', 'age')

DEBUG:root:a_state_z, ('state', 'region'), ('state', 'region')

DEBUG:root:a_region, ('region',), ('region',)

DEBUG:root:a_state, ('state', 'region'), ('state', 'region')

DEBUG:root:abortion, ('state', 'region'), ('state', 'region')
DEBUG:root:abortion, ('age',), ('age',)
DEBUG:root:abortion, ('eth',), ('eth',)
DEBUG:root:abortion, ('educ',), ('educ',)
DEBUG:root:abortion, ('male', 'eth'), ('male', 'eth')
DEBUG:root:abortion, ('educ', 'age'), ('educ', 'age')
DEBUG:root:abortion, ('educ', 'eth'), ('educ', 'eth')
```

In addition, manually checking for subscript mismatches according to https://github.com/bbbales2/regressions/pull/41#discussion_r776108518, raised no exceptions and no subscript mismatched when ran with the above line uncommented.

**Comment by bbbales2** [comment]
Hmm, I guess if this wasn't reproducible I'll close this. If it's a problem it'll pop up again.
