### ISSUE TITLE
Parameter/Input Types

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#86]
Right now we're assuming parameters and data are NumericTypes. This makes it awkward to work with Integer or Real constants.

See conversation starting [here](https://github.com/bbbales2/regressions/pull/81#discussion_r872488874).

**Comment by bbbales2** [comment]
I think the idea of assuming everything is real works for parameters, but it'd be really awkward for data.

For factor data (the things that form the subscripts) we kinda just want to work with everything (and if the factors are integers... great!).

I kinda want to go ahead and add signatures for the input dataframes. That also helps with editors. What if we do strongly typed input dataframes?

I'm hesitant to do this only because it seems convenient to automatically infer at runtime which things are parameters and which are data, but convenience is the argument for not-strong-typing and we said we want strong typing so doesn't that mean we'd need to be willing to give up this convenience?

**Comment by Dashadower** [comment]
How about using casting functions to indicate what type the data should be treated as? I think it's literally a matter of syntax compared to type signature for the input dataframe, but inside the model code.

**Comment by bbbales2** [comment]
Hit me with some pseudo-code

**Comment by Dashadower** [comment]
I'm gonna borrow input data from another issue:
```
date,hteam,ateam,hscore,ascore,hadiff,hnumber,anumber
2019-10-22,TOR,NOP,130.0,122.0,8.0,0,1
2019-10-22,LAC,LAL,112.0,102.0,10.0,0,2
2019-10-23,CHA,CHI,126.0,125.0,1.0,0,3
2019-10-23,IND,DET,110.0,119.0,-9.0,0,4
2019-10-23,ORL,CLE,94.0,85.0,9.0,0,5
2019-10-23,BKN,MIN,126.0,127.0,-1.0,0,6
```

If I wanted to use `anumber` as an integer, I'd just do something like:
```
hscore' ~ normal(2.3 ^ int(anumber), 1.0)
```
Just like python. I'd say we can make the default type as real? Since for non-numeric data that's only used for subscripts(`data, hteam, ateam`), we won't be doing operations.
