### ISSUE TITLE
Not checking that columns actually exist in source dataframes

### ISSUE THREAD

**Issue by bbbales2** [bbbales2/regressions#89]
`score_diff` didn't actually exist in input dataframe. I got this error:

```
rat.exceptions.CompileError: An error occurred while compiling code at (0:27):
score_diff' ~ normal(skill[hteam] - skill[ateam], sigma);
                           ^~~~~
Subscript hteam not found in dataframe of primary variable score_diff
```

**Comment by Dashadower** [comment]
Does `hteam` exist?

**Comment by Dashadower** [comment]
If you can link model code and data, I can take a closer look.

**Comment by bbbales2** [comment]
I added a test in a PR over [here](https://github.com/bbbales2/regressions/pull/93)

**Comment by Dashadower** [comment]
Closing since error was from a different source. But we should revisit and perhaps add a check for parameters without priors set.
